### ISSUE TITLE
Norwegian translation (nb)

### ISSUE THREAD

**Issue by JanConGitHub** [ropod7/ethereumprice#1]
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the ethereumprice.ropod7 package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ethereumprice.ropod7\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-09-23 21:31+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../qml/Main.qml:26
msgid "Ethereum Market Price"
msgstr "Markedspris Ethereum"

#: ../qml/Main.qml:33 ../qml/Main.qml:47 ../qml/Main.qml:63
msgid "Loading..."
msgstr "Laster..."

#: ../qml/Main.qml:85
msgid "Refresh"
msgstr "Oppfrisk"

#: ethereumprice.desktop.in.h:1
msgid "Ethereum Price"
msgstr "Pris Ethereum"

**Comment by ropod7** [comment]
Thank you! Done!
